export const HOME_ROUTE = '/'
export const REGISTRATION_ROUTE = '/registration'
export const LOGIN_ROUTE = '/login'
export const SERVICES_ROUTE = '/services'
export const TOYS_ROUTE = '/toys'
export const CART_ROUTE = '/cart'
export const PROFILE_ROUTE = '/profile'
export const ADMIN_ROUTE = '/admin'